---
    - name: Does the Google apt file exist?
      command: test -f /etc/apt/sources.list.d/google-chrome.list
      register: google_apt_exists
      ignore_errors: true

    - name: Download chrome-stable
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/google-chrome-stable_current_amd64.deb
      when: google_apt_exists.rc == 1

    - name: Install chrome-stable
      shell: dpkg -i /tmp/google-chrome-stable_current_amd64.deb
      when: google_apt_exists.rc == 1

    - name: Remove installation package
      file: path=/tmp/google-chrome-stable_current_amd64.deb state=absent
      when: google_apt_exists.rc == 1
    